### ISSUE TITLE
publishing multiple mxds

### ISSUE THREAD

**Issue by steveoh** [agrc/grunt-arcgis-press#16]
currently we have a `mxdPath` property for the mxd, how should we allow for multiple maps? 

Suggestion 1
1. Store only the base path to the mxd
   - That way we can run on multiple machines by only having the mxd name be the same.
2. Store the paths as an array and read from them?
   - Not sure I like this idea

What do you think?

**Comment by stdavis** [comment]
I was assuming #1. Maybe the property needs to be renamed to something like
`mxdBasePath`.

On Mon, Mar 9, 2015 at 10:45 AM, steveoh notifications@github.com wrote:

> currently we have a mxdPath property for the mxd, how should we allow for
> multiple maps?
> 
> Suggestion 1
> 1. Store only the base path to the mxd
>    - That way we can run on multiple machines by only having the mxd
>      name be the same.
>      1. Store the paths as an array and read from them?
>    - Not sure I like this idea
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/grunt-arcgis-press/issues/16.

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC
