### ISSUE TITLE
Logo Ideas

### ISSUE THREAD

**Issue by steveoh** [agrc/grunt-arcgis-press#5]
This came from irc: 

> i was thinking a waiter icon holding up a globe but due to the new name i'm thinking something like this "pressing" a map

![btfou irc](https://cdn3.iconfinder.com/data/icons/print-icons/512/Offset_Print-512.png)

**Comment by stdavis** [comment]
I like this logo. I think that we should go with it. Can we use it?

**Comment by steveoh** [comment]
i think it's creative commons licensed... you'd have to ask @btfou where he grabbed it from.

**Comment by btfou** [comment]
@steveoh @stdavis https://www.iconfinder.com/icons/112389/design_industry_graphic_industry_offset_print_offset_printer_press_print_printing_raw_simple_icon

Yep it's two $. I thought the concept was cool but envisioned a map being pressed. If I had any real design ability I'd give it a go.

**Comment by stdavis** [comment]
It's ours to do with what we want.
https://dl.dropboxusercontent.com/u/14814828/press.ai
https://dl.dropboxusercontent.com/u/14814828/press.svg

**Comment by steveoh** [comment]
![press](https://cloud.githubusercontent.com/assets/325813/6882906/25168c48-d55c-11e4-851c-5fa3765fee68.png)

**Comment by btfou** [comment]
Null Island...nice.

**Comment by stdavis** [comment]
Awesome. 

-Scott
