### ISSUE TITLE
Crazy Idea

### ISSUE THREAD

**Issue by stdavis** [agrc/grunt-arcgis-press#6]
Just thinking of how to make this project be able to run on travis so that travis can do our deploys.

What if we made a gptask on the server that accepted an mxd and associated configs and then published the service via the gptask? That way travis could just send it the mxd that's in the repo along with configs?

**Comment by steveoh** [comment]
That's a cool idea but I don't know if we are making a bad security decision by putting the mxd with connection information to the data with a user that could be able to edit out in the wild... I'm not sure if I'm being paranoid or not

**Comment by stdavis** [comment]
True. I've never thought about it before but if someone opened up one of
our mxd's within the state network they could edit data. It's SO convenient
to have them versioned along with the rest of our code but maybe it's a bad
idea.

Still this idea doesn't depend on versioning the mxd. We could keep them on
a share somewhere and just version the service configs. Then this task
could just send configs to a gp task. This would have the advantage of
forcing us to keep all of the mxd's in one place.

On Thu, Feb 19, 2015 at 6:13 PM, steveoh notifications@github.com wrote:

> That's a cool idea but I don't know if we are making a bad security
> decision by putting the mxd with connection information to the data with a
> user that could be able to edit out in the wild... I'm not sure if I'm
> being paranoid or not
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/grunt-arcgis-press/issues/6#issuecomment-75173081
> .

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@ScottAGRC https://twitter.com/ScottAGRC

**Comment by steveoh** [comment]
I like that idea very much. There can be a setting in the task for mxd
location.
